export const data = [
  {
    attributes: [
      { value: "Chocolate", trait_type: "Body" },
      { value: "Shirt-and-sweater", trait_type: "Clothes" },
      { value: "Blurple", trait_type: "Color Background" },
      { value: "Calm", trait_type: "Eyes" },
      { value: "Bullet", trait_type: "Helmets" },
      { value: "Munch", trait_type: "Mouth" },
      { value: "Crosses", trait_type: "Texture" },
    ],
    description: "",
    image: "ipfs://bafkreibwiez7d6e5ubadmvcxo6nnzyowqd52nhj3fivep6i3b5kkwatnfq",
    name: "Bueno Demo #1",
  },
  {
    attributes: [
      { value: "Soft", trait_type: "Body" },
      { value: "Rings", trait_type: "Clothes" },
      { value: "Blurple", trait_type: "Color Background" },
      { value: "Calm", trait_type: "Eyes" },
      { value: "Fishbowl", trait_type: "Helmets" },
      { value: "Smile", trait_type: "Mouth" },
      { value: "Flower", trait_type: "Texture" },
    ],
    description: "",
    image: "ipfs://bafkreicgptsbq7jjgkeetzsupujzoxufcofcekz2qpe7bddjbl4oeviiue",
    name: "Bueno Demo #2",
  },
  {
    attributes: [
      { value: "Seafoam", trait_type: "Body" },
      { value: "Shell", trait_type: "Clothes" },
      { value: "Ruby", trait_type: "Color Background" },
      { value: "Simple", trait_type: "Eyes" },
      { value: "Guard", trait_type: "Helmets" },
      { value: "GM", trait_type: "Mouth" },
      { value: "Flower", trait_type: "Texture" },
    ],
    description: "",
    image: "ipfs://bafkreiazazss2kunodlimqmagdi7qdim35ndwafy4o7xn7pqlnqk4blfbm",
    name: "Bueno Demo #3",
  },
  {
    attributes: [
      { value: "Seafoam", trait_type: "Body" },
      { value: "Bueno", trait_type: "Clothes" },
      { value: "Yellow", trait_type: "Color Background" },
      { value: "Calm", trait_type: "Eyes" },
      { value: "Cardboard", trait_type: "Helmets" },
      { value: "Munch", trait_type: "Mouth" },
      { value: "Sparkles", trait_type: "Texture" },
    ],
    description: "",
    image: "ipfs://bafkreicdtljlj2jx6pxermi3ryozhd5fuotnn5dhywnt4px6e2pu75vzqi",
    name: "Bueno Demo #4",
  },
  {
    attributes: [
      { value: "Seafoam", trait_type: "Body" },
      { value: "Robot", trait_type: "Clothes" },
      { value: "Sky", trait_type: "Color Background" },
      { value: "Glam Shades", trait_type: "Eyes" },
      { value: "Munch", trait_type: "Mouth" },
      { value: "Curves", trait_type: "Texture" },
    ],
    description: "",
    image: "ipfs://bafybeihwt44ffskgksf3jh6so756z4iurwv3yjmcl4ddipnvhqn4upobte",
    name: "Bueno Demo #5",
  },
  {
    attributes: [
      { value: "Seafoam", trait_type: "Body" },
      { value: "Lines", trait_type: "Clothes" },
      { value: "Sky", trait_type: "Color Background" },
      { value: "Derpy", trait_type: "Eyes" },
      { value: "Bullet", trait_type: "Helmets" },
      { value: "Fangs", trait_type: "Mouth" },
      { value: "Flower", trait_type: "Texture" },
    ],
    description: "",
    image: "ipfs://bafybeiambuwtwzzing4bextw7twnjka3dqkocpcbcwfynd5u6hxjut7nri",
    name: "Bueno Demo #6",
  },
  {
    attributes: [
      { value: "Chocolate", trait_type: "Body" },
      { value: "Glam", trait_type: "Clothes" },
      { value: "Sky", trait_type: "Color Background" },
      { value: "Glam Shades", trait_type: "Eyes" },
      { value: "Bike", trait_type: "Helmets" },
      { value: "Lips", trait_type: "Mouth" },
      { value: "Waves", trait_type: "Texture" },
    ],
    description: "",
    image: "ipfs://bafkreiddypezsl4stsayzg5y3tilozqgg3mbc6lzdik5flctpdzyj2znia",
    name: "Bueno Demo #7",
  },
  {
    attributes: [
      { value: "Chocolate", trait_type: "Body" },
      { value: "Shell", trait_type: "Clothes" },
      { value: "Hot-Pink", trait_type: "Color Background" },
      { value: "Cyclop", trait_type: "Eyes" },
      { value: "Bullet", trait_type: "Helmets" },
      { value: "Fang", trait_type: "Mouth" },
      { value: "Mess", trait_type: "Texture" },
    ],
    description: "",
    image: "ipfs://bafkreic5ntgrru7by32ubabmdapglnzu2xjqqg3pybq6sa7quz4i345mpm",
    name: "Bueno Demo #8",
  },
  {
    attributes: [
      { value: "Blue", trait_type: "Body" },
      { value: "Sweater", trait_type: "Clothes" },
      { value: "Hot-Pink", trait_type: "Color Background" },
      { value: "Derpy", trait_type: "Eyes" },
      { value: "Bullet", trait_type: "Helmets" },
      { value: "Fang", trait_type: "Mouth" },
      { value: "Sparkles", trait_type: "Texture" },
    ],
    description: "",
    image: "ipfs://bafkreia6gs55kxdyd63djim5bhnprlyg5f2esbdpzv6mg5zpmrc4kzvrxe",
    name: "Bueno Demo #9",
  },
  {
    attributes: [
      { value: "Cream", trait_type: "Body" },
      { value: "Shirt and sweater", trait_type: "Clothes" },
      { value: "Yellow", trait_type: "Color Background" },
      { value: "Simple", trait_type: "Eyes" },
      { value: "Bullet", trait_type: "Helmets" },
      { value: "Open-Mouth", trait_type: "Mouth" },
      { value: "Dots", trait_type: "Texture" },
    ],
    description: "",
    image: "ipfs://bafkreiaftv3cajvjzdvll5q5vkq7ts36xqgmdr35kbcq3fhsqwvaivuf4i",
    name: "Bueno Demo #10",
  },
];
